### ISSUE TITLE
Unknown handling seems wrong

### ISSUE THREAD

**Issue by w33ble** [lukeed/mri#4]
It's a little odd that the unknown function requires that aliases be defined to match defined flags. It means that exact matches "fail", but because of the way the parser works, prefixed flags do not. Example:

```js
const mri = require('mri')
const opts = { boolean: ['check'], unknown: (arg) => console.log('unknown arg:', arg) }

// this hits the unknown handler
mri(['--check'], opts)

// this just works
const args = mri(['--no-check'], opts)
```

I'm curious why the alias requirement exists. Why not just continue if there's an exact flag match?

**Comment by lukeed** [comment]
Interesting, thanks! I haven't checked out the code in a while to be honest, but I'll try and make my way back to this sometime this week.

I think what needs to happen is all `boolean` and `string` keys need to be written _into_ the alias map on options parsing. 🤔 Will check it out. I do remember that `unknown` was a last-second type of addition.
