### ISSUE TITLE
null default arguments cause an error

### ISSUE THREAD

**Issue by ascorbic** [lukeed/mri#7]
I encountered this error in microbundle, which uses mri via sade. One of microbundle's arguments is a boolean, but the default is null because the actual default depends on other arguments (`--compress` defaults to true when targetting web, and false when targetting node). A change introduced in mri@1.1.2 causes parsing to break with the error:

> Cannot read property 'push' of undefined

...which is being thrown [here](https://github.com/lukeed/mri/blob/master/lib/index.js#L50). Presumably this is because it only accepts, strings numbers and booleans. I don't know if `null` is a valid value for defaults, but it seems like this is a regression.

**Comment by lukeed** [comment]
Hey, sorry about that but thanks for the quick report!

Can you do me a favor & try to replace that line with this instead?

```diff
- opts[typeof opts.default[k]].push(k);
+ (opts[typeof opts.default[k]] || []).push(k);
```

**Comment by ascorbic** [comment]
That works!

**Comment by lukeed** [comment]
Great, thanks! Adding a test & the fix. Patch incoming.
